### ISSUE TITLE
Why not joi based?

### ISSUE THREAD

**Issue by martinheidegger** [hapijs/bossy#33]
I wonder if it would be awesome to have a joi based cli parser?!

**Comment by sericaia** [comment]
In order to validate all arguments received? yeah, it seems to be great. 

Do you want to summit a PR?

**Comment by hueniverse** [comment]
Was this implemented?

**Comment by sericaia** [comment]
Hi @martinheidegger, was this fixed by this PR https://github.com/hapijs/bossy/pull/35 ?

**Comment by martinheidegger** [comment]
Sorry for the late reply, was sick recently and didn't have time to answer. No this was not fixed by #35. #35 changed the implementation to a Joi based format (which is good in itself) but it didn't change the way properties were declared. I thought a specification like:

```JavaScript
var definition = {
    h: {
        description: 'Show help',
        alias: 'help',
        type: 'boolean'
    },
    n: {
        description: 'Show your name',
        alias: 'name'
    }
};
```

to be written as:

```JavaScript
var help = Joi.boolean().description('Show help');
var name = Joi.any().description('Show your name');
var definition =  Joi.object({
    h: help,
    help: help,
    n: name,
    name: name
});
```

**Comment by Marsup** [comment]
While it's certainly doable, I'm not sure it's a win for API clarity, especially for the alias part (which would be renames in joi terms). And it will probably limit the enhancements you might want to do here if they make no sense in the joi world.

**Comment by martinheidegger** [comment]
The alias part is a way that I (with my limited joi skill) came up with. Even after heavy thinking I didn't find a(ny) difference in how the specification of the input of an API would be different from the specification of a command line tool. May i dare a challenge?
